### PR TITLE
Refactored & added/improved unit tests

### PR DESCRIPTION
**Pull request by rafaelklaessen**

### CODE REVIEW

**Review by RyanZim — CHANGES_REQUESTED** [review]
NACK on the JSDoc types; please remove them.

Also, please rebase and merge b78e26fab83db08c2380b7c3c212695fefa83723 into fe30e190b4ecbdc39b62c76a0bc85486b89d2851.

Other than that, looks OK.

**Comment by RyanZim** [comment]
While you're at it, could remove Node 5 from the `.travis.yml` and add 6 & 8. It's up to you.

**Comment by RyanZim** [comment]
@rafaelklaessen Please squash cdd83ea into 8825ef8 and amend the commit message for the resulting commit. Also, please move the changelog changes in d18b7cf and a847a94 into a seperate, changelog-only commit. Let me know if you'd prefer that I do this.

**Comment by rafaelklaessen** [comment]
I'd prefer if you do it :)

**Comment by RyanZim** [comment]
Rebased locally and landed in ebf9ab8.

**Pull request closed without merging**
